name: green_thumb_cloud_next_25
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_picture_taker: ^0.2.0
  cross_file: ^0.3.4+2
  http: ^1.3.0
  image: ^4.5.2
  image_picker: ^1.1.2
  device_info_plus: ^11.3.0
  flutter_markdown: ^0.7.6+2
  collection: ^1.19.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/woman-gardening.png
    - assets/tomato_trellis.jpeg
    - assets/patio_garden.jpeg
    - assets/wildflowers.jpeg
    - assets/product-images/

